image: docker:24

services:
  - docker:24-dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

stages:
  - build

build-docker-image:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # install dependencies & build Angular
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm install --frozen-lockfile
    - pnpm run build:prod

    # build Docker image
    - docker build -t $IMAGE_NAME .

    # push image to GitLab registry
    - docker push $IMAGE_NAME
  only:
    - main
